---
title: "Guide for GRAs"
output:
  html_document:
    toc: true
    toc_float: true
---

<br>

### Purpose
The purpose of this document[^1] is designed to help students understand general expectations for work hours, face time, sick leave, and vacation time, when supported by a Graduate Research Assistantship (GRA). Expectations can vary from country to country and from one PI to the next, so below I have outlined expectations for GRAs in my lab.  This also serves as a general guideline for students working in my lab and supported on fellowships or other types of assistantship funding.  

<br>
  
### Work hours
GRAs are part-time salaried positions that expect 19.6 hours of work per week during the academic year and for 40 hours per week during academic breaks and summer sessions.  Additional time directed towards research is expected when you are enrolled in credit hours for research and/or thesis/dissertation writing.  Because a GRA is a salaried position, these work hours are the expectation and not recorded on a time sheet.  The actual amount of time spent on research can vary considerably.  You are expected to manage your time effectively.  Poor time management at the beginning of a graduate program can be especially damaging because even as little as 10 minutes per day spent off task adds up to more than a week of time lost by the end of the year.  Now, consider what an opportunity that time offers!  **_<span style="color:black">If you spend just 10 minutes per day on writing your first manuscript, you’ll have spent more than an entire 40-hour work week by the end of the first year.</span>_** Moreover, there is no fixed amount of time required to complete your master's or dissertation. Thus, the sooner you complete the outlined projects, the sooner you will graduate.[^2]

<br>

### Face time
Students should develop strategies for optimal productivity.  Graduate students in my lab are allowed to work from home or any other place that allows them increased productivity.  However, there are benefits to being seen and present in our department on a regular basis (this is called “face time”).  Your colleagues and professors will notice if you are working in the building daily and you will gain a reputation as being hard working and reliable. **_<span style="color:black">This reputation will be useful once you are looking for a job and may need references from more than one professor in the department.</span>_** Being present in the department daily will also increase your opportunity for collaboration with other students and enable you to learn from others you interact with.  Naturally, newer students will be present at the department more often than those who have only the thesis or dissertation left to complete.  However, being present without being productive is not a good use of time and will not lead to benefits.  For this reason, it is your responsibility to set a work schedule for yourself that will maximize both productivity and visibility. 

<br>

### Sick leave
I do not expect you to work while you are sick.  It’s better to stay home and recover.  You should notify me via email if you will be out of the office due to illness.  If longer periods of leave are needed, such as for family/child illness, medical issues, or funeral leave, please let me know so we can discuss a plan for your work to avoid setbacks.

<br>

### Requesting vacation time 
Time off for vacation requires my approval beforehand.  This will be based upon successful performance of job duties, grades, expectations, and progress towards completion of your research projects.  **_<span style="color:black">Additional time off will be granted for exceptional performance.</span>_** See vacation time extimate below.

<br>

### Vacation time estimate
It is unlikely for you to receive approval of a request for more vacation time than an employee with a full-time 12-month appointment would accumulate.  For example, in the 1st through 5th year of employment, **_<span style="color:black">full-time employees accrue one vacation day per month</span>_**. Thus, a person who began employment on August 15th would accrue four vacation days by December 15th.  This time can be combined with UNL holidays (when UNL is closed) for a total time off of 2-weeks during the winter break.  This amount of vacation during the winter holiday assumes no vacation time was taken prior to the winter holiday.  The following year, it would be possible to take up to 3 weeks off during the winter break.  Since time during academic breaks, winter holiday, and summers offer the opportunity and expectation to complete more research (40 hours per week), taking this time off can be costly to your research progress.  Attending class is also expected, so classes should not be skipped for vacation either.  For this reason, approval of vacation time is based performance and progress towards the degree.

<br>

[^1]: This document was written by Sydney Everhart and has been reviewed by the human resources expert in our business office at UNL.  The purpose of this document is designed to help students understand general expectations and is not meant to be a legally binding document.  Last update on Nov. 22, 2017.

[^2]: Research projects do not always follow a straight-line trajectory. Lessons may be learned and modificiations may be made during the process of completing the outlined research projects that require deviation from the original plan. Despite this possibility, having a clearly defined plan for your work from the beginning of your graduate program that is updated on a regular basis will improve the likelihood you are able to graduate as soon as possible.