---
title: "Join Our Lab"
output:
  html_document:
    toc: true
    toc_float: true
---

Despite the popularized image of a lone scientist, the reality is that science is actually quite social.  Beyond the literature, your peers and other scientists will represent a key source of ideas, references, feedback, and skills.  By joining our lab group, you have become a member of the team.

<br>

### Undergraduate Students
Working in my lab is a great place to learn some basic microbiology and molecular genetic techniques. We have a limited number of paid hourly positions. Students interested in conducting a UCARE or senior thesis project in my lab are encouraged to contact me directly at everhart@unl.edu

<br>

### Graduate Students
Deciding to attend graduate school and selecting an advisor for your studies is an important step.  I take my role as an advisor seriously and it is my goal to give you the best opportunity for success.  Please read this letter that I have written to new graduate students.  Graduate studies in my lab will require funding to support your work, so I will advertise on my website when I have projects and funding available to support a student.  Please also consider seeking funding from federal agencies (NSF, USDA, EPA) to partially or fully support your graduate studies.  If you are interested in applying for a fellowship, please contact me at least 1-year before your intended start date so that we can work together to develop your proposal.  My email address is everhart@unl.edu

<br>

### Postdoctoral Scholars
Funding for postdoctoral scholars is limited and I will advertise on my website as I have funding available.  Please also consider seeking funding from federal, private, and governmental agencies.  If you are interested in applying for a fellowship, please contact me at least 1-year before your intended start date so that we can work together to develop your proposal.  My email address is everhart@unl.edu

<br>

### Visiting Scholars
Funding for this type of position is usually obtained from the scholar's home country or institution, with the duration determined by the funding agency and the goal of your visit.  Visiting scholars from all nations and institutions are encouraged to contact me about the opportunity to work in my lab and collaborate on projects.  Email me at everhart@unl.edu

<br>

### Still not sure that my lab is the right fit for you?
Contact me!  Let's talk about your research interests / goals and how we might be able to work together to achieve them.  My office is located in 406G Plant Science Hall on the East Campus at the University of Nebraska - Lincoln.  If you can't make a visit, I'd be happy to meet with you via Skype.  My email address is everhart@unl.edu