---
title: "Advice to New Faculty"
output:
  html_document:
    toc: true
    toc_float: true
---

## 

<br>

### Advice to New Faculty

I was invited to speak as part of a new faculty orientation workshop hosted by Dean Richard Bischoff for those in the Institute of Agriculture and Natural Resources on August 28, 2019.  The following list of tips were a prepared as part of my involvement on a faculty panel for the workshop.  The focus of the panel discussion was advice to new faculty on research

## Disclaimer

The first thing I want to do is to provide a dislaimer so that readers have a reasonable expectation about the forthcoming advice. The following advice comes to you from someone who is in a collegial department that is mostly functional but not toxic.  This is important because there are departments on campus that I would classify as toxic. I also come from a department that is small.  It is likely we are currently the smallest department within IANR, with about 16 faculty.  I say about because some of our faculty are non-tenure line positions and some are administrators, so it depends on how you do the math here. 

## Top 10 Tips for Tenure

1. *Print out your position description and pin it to your wall or tape it to your monitor.*  This document should be your roadmap for how you should spend your time and invest your resources.  Not all activities will have direct relevance to your position description, however, if you are able to make a logical justification for an activity in how it indirectly supports your position description then you've got a green light to engage in that activity. Items that cannot be reasonably justified as achieving your position description should be avoided or strictly limited.  

2. *Cultivate positive relationships with office staff and business office personal.*  These are the people that you will rely on when hiring personnel, navigating paperwork and institutional processes, and helping you out with last minute grant proposal submissions.  These are not the people you want to piss off.  Instead, these are the people who can help teach you how our instutition functions and connect you with the right people.  Make these people your friends, praise their work, and appreciate their role in our institution.  Your kindness is a good investment.

3. *Be prepared to not be the best.*  Although you may have been a top graduate student in your program or field, you probably won't be the top grant winner or performer as a new faculty member. Being a top grant winner varies drastically depending on your area of research and good research does not always equate with dollars brought in.  Although you can't expect to be the top in every way, being invested in your mentoring, research, department, and institution, can be rewarding and also gain you attention for your efforts.  Don't get discouraged if you're no longer the best.

4. *Get advice from several senior trusted faculty members.*  I often hear people complain that their faculty mentor doesn't engage them.  This is common and, in reality, it is your responsibility as a junior faculty member to seek out the advice of your mentor. However, don't just rely on your assigned mentor, reach out to multiple senior trusted faculty members in your department.  For example, not sure if you should do that service work you were just invited to do?  Ask a senior trusted faculty member!  Facing a difficult situation with a student or postdoc?  Ask a senior trusted faculty member.  Not sure what you should do 
