---
title: "Research in the Everhart Lab"
output:
  html_document:
    toc: true
    toc_float: true
---
<br>

## Publications

<br>

### **Peer-Reviewed Publications:**
^†^ = Co-first author; ^‡^ = Corresponding author

#### 2017

1. Kamvar, Z.N., B.S. Amaradasa, R. Jhala, S. McCoy, J.R. Steadman, S.E. Everhart^‡^. 2017. Population structure and phenotypic variation of *Sclerotinia sclerotiorum* from dry bean (*Phaseolus vulgaris*) in the United States. *PeerJ* 5:e4152 https://doi.org/10.7717/peerj.4152
1. Grunwald, N.J., S.E. Everhart, B.J. Knaus, and Z.N. Kamvar. 2017. Best practices for population genetic analyses. *Phytopathology* 107:1000-1010. doi: 10.1094/PHYTO-12-16-0425-RVW
2. Dowling, M., G. Schnabel, H. Boatwright, and S.E. Everhart^‡^. 2017. Novel gene-sequence markers for isolate tracking within *Monilinia fructicola* lesions. *Pest Management Science*. doi: 10.1002/ps.4544
3. Mirorini, T.J.J., C.G. Raetano, and S.E. Everhart^‡^. 2017. Control of white mold of dry bean and residual activity of Fungicides applied by chemigation. *Crop Protection* 94:192-202.

#### 2016

5. Amaradasa, B.S., and S.E. Everhart^‡^. 2016. Effects of sublethal *Fungi*cides on mutation rates and genomic variation in fungal plant pathogen, *Sclerotinia sclerotiorum*. PLoS One. 11 (12): e0168079. doi: 10.1371/journal.pone.0168079.
5. Dugan, F.M., and S.E. Everhart. 2016. Cryptic species: A leitmotif of contemporary mycology has challenges and benefits for plant pathologists. *Plant Health Progress*. DOI:10.1094/PHP-RV-16-0046
6. de Bem, B.P., A. Bogo, S.E. Everhart, R.T. Casa, M.J. Goncalves, J.L. Marcon, L.R. Rufato, F.N. Silva, R. Allebrandt, I.C. da Cunha. 2016. Effect of four training systems on the temporal dynamics of downy mildew in two grapevine cultivars in southern Brazil. *Topical Journal of Plant Pathology*. DOI 10.1007/s40858-016-0110-8.
7. Tabima J.F., S.E. Everhart, M.M. Larsen, A.J. Weisberg, Z.N. Kamvar, M.A. Tancos, C.D. Smart, J.H. Chang, and N.J. Grünwald. 2016. Microbe-ID: An open source toolbox for microbial genotyping and species identification. *PeerJ* 4:e2279 DOI 10.7717/peerj.2279
8. Dowling, M., P.K. Bryson, H. Boatwright, J.R. Wilson, Z. Fan, G. Schnabel, S.E. Everhart, and P. Brannen. 2016. Effect of Fungicide application on *Monilinia fructicola* population diversity and transposon movement. *Phytopathology* 103:1504-1512. DOI:10.1094/PHYTO-03-16-0127-R

#### 2015

10. Chen, F., S.E. Everhart^†^, P.K. Bryson, C.L., X. Song, X.L., G. Schnabel. 2015. Fungicide induced transposon movement in Monilinia fructicola. Fungal Genetics and Biology 85:38-44.
10. Everhart, S.E., and H. Scherm. 2015. Clonal disease foci of Monilinia fructicola during brown rot epidemics within peach tree canopies.*Phytopathology*105:542-549.
11. de Bem, B.P., Bogo, A., S. Everhart, R.T. Casa, M.J. Goncalves, J.L.M. Filho, and I.C. da Cunha. 2015. Effect of Y-trellis and vertical shoot positioning training systems on downy mildew and botrytis bunch rot of grape in highlands of southern Brazil. *Scientia Horticulturae* 185:162-166.

#### 2014

13. Schnabel, G., F. Chen, S.E. Everhart, W.C. Bridges and X.L. Liu. 2014. Studies on sensitivity reduction in solo and mixture treatments and Fungicide-induced mutagenesis in *Monilinia fructicola*. In: H.W. Dehne, H.B. Deising, U. Gisi, B. Fraaije, U. Gisi, D. Hermann, A. Mehl, E.C. Oerke, P.E. Russel, G. Stammler, K.H. Kuck, H. Lyr (Eds). “Modern Fungicides and Antifungal Compounds”, Vol. VII, pp 263-268. 2014 Deutsche Phytomedizinische Gesellschaft, Braunschweig, ISBN: 978-3-941261-13-6.

#### 2013

14. Everhart, S.E., A. Askew, L. Seymour, and H. Scherm. 2013. Spatio-temporal patterns of pre-harvest brown rot epidemics within individual peach tree canopies. *European Journal of Plant Pathology* 135: 499–509.

#### 2012

15. Everhart, S.E., A. Askew, L. Seymour, T.C. Glenn, and H. Scherm. 2012. Spatial patterns of brown rot epidemics and development of microsatellite markers for analyzing fine-scale genetic structure of Monilinia fructicola populations within peach tree canopies. Online. *Plant Health Progress* doi:10.1094/PHP-2012-0723-04-RS.

#### 2011

16. Everhart, S.E., A. Askew, L. Seymour, I.J. Holb, and H. Scherm. 2011. Characterization of three-dimensional spatial aggregation and association patterns of brown rot symptoms within intensively mapped sour cherry trees. *Annals of Botany* 108: 1195–1202.

#### 2010

17. Everhart^‡^, S.E. 2010. Collection and identification of grapevines (*Vitis*) from the tree canopy of select forests in the southeastern United States. Castanea 75: 141–149.
17. Keller, H.W., and S.E. Everhart 2010. Importance of Myxomycetes in biological research and teaching. *Fungi* 3(1): 13–27.

#### 2009

19. Everhart, S.E., J.S. Ely, and H.W. Keller. 2009. Evaluation of tree canopy epiphytes and bark characteristics associated with corticolous myxomycetes. *Botany* 87: 509–517.
19. Keller, H.W., S.E. Everhart, M. Skrabal, and C.M. Kilgore. 2009. Tree canopy biodiversity in temperate forests: Exploring islands in the sky. *Southeastern Biology* 56: 52–74.

#### 2008

21. Everhart, S.E., and H.W. Keller. 2008. Influence of bark pH on the occurrence and distribution of tree canopy myxomycete species. *Mycologia* 100: 191–204.
21. Everhart, S.E., and H.W. Keller. 2008. Life history strategies of corticolous myxomycetes: The life cycle, fruiting bodies, plasmodial types, and taxonomic orders. *Fungal Diversity* 29: 1–16.
22. Keller, H.W., C.M. Kilgore, S.E. Everhart, G. Carmack, C. Crabtree, and A. Scarborough. 2008. Myxomycete plasmodia and fruiting bodies: Unusual occurrences and user friendly study techniques. *Fungi* 1: 24–37.
23. Keller, H.W., and S.E. Everhart 2008. Myxomycete species concepts, monotypic genera, the fossil record, and additional examples for good taxonomic practice. *Revista Mexicana de Micologia* 27: 9–19.
24. Kilgore, C.M., H.W. Keller, S.E. Everhart, A. Scarborough, K. Snell, M. Skrabal, C. Pottorff, and J.S. Ely. 2008. Tree canopy research and student experiences using the double rope climbing method. *Journal of Botanical Research Institute of Texas* 2: 1309–1336.

<br>

### **Books, Chapters, and R packages:**

26. Keller, H.W., S.E. Everhart, and C.M. Kilgore. 2017. The Myxomycetes: Biology, life cycle, genetics and reproduction. In: Stephenson, S. and C. Lado (eds) “Myxomycetes: Biology, Systematics, Biogeography and Ecology”, Elsevier, Atlanta, GA. 
26. Kamvar, Z.N., Tabima, J.F., Everhart, S.E., Brooks, J.C., Krueger-Hadfield, S.A., Sotka, E. and Grunwald, N.J., 2016. Package ‘poppr’. https://cran.r-project.org/web/packages/poppr/index.html
27. Grunwald, N.J., Z.N. Kamvar, and S.E. Everhart. 2015. Population Genetics in R. Online book: http://grunwaldlab.github.io/Population_Genetics_in_R/
28. Everhart, S.E., T.F. Tabima, and N.J. Grünwald. 2014. *Phytophthora ramorum*. In: Dean, R.A., A. Lichens-Park, and C. Kole (eds) “Genomics of Plant Associated Fungi and Oomycetes”, Springer, New York, NY. Pp. 159-174.