---
title: "Research in the Everhart Lab"
output:
  html_document:
    toc: true
    toc_float: true
---
In the Everhart lab, our goal is to understand how and why disease outbreaks occur.  Using genotyping and quantitative data analysis approaches, our goal is to determine factors that may be predictive of disease outbreaks.  Such factors may involve aspects of the host (cultivar or species affected), management technique (crop rotation, tilling, or pesticide applications), environment (local temperatures, rainfall/irrigation, soil type), pathogen phenotype (aggressiveness, fungicide sensitivity, growth rate), or biology of the pathogen (mechanisms of spread, sexual recombination).

Current research in the Everhart lab is focused on two important fungal plant pathogens, Sclerotinia sclerotiorum and Rhizoctonia solani, which affect several economically important crops in Nebraska.  Results of our work are important for management recommendations.

----

## Current Research Areas

### Fungicide resistance emergence
Fungicide resistance is costly for manufactures, growers, and the environment; nevertheless mechanisms driving the emergence of resistance remain unknown.  Interestingly, stress has been shown to increase mutation rates in E. coli, leading to emergence of antibiotic resistance. Although this is a recognized risk for fungicides, little is known about fungal evolution in the context of various stressors.  Thus, the goal of our research is to unravel the mechanisms of fungicide resistance emergence by first examining and characterizing factors that affect mutation rates in fungi.  Presently, we work with Sclerotinia sclerotiorum as a model system to characterize the effects of stressors on genomic mutation rates and determine if these lead to heritable fungicide resistance. S. sclerotiorum is an economically important fungal pathogen that causes disease on over 400 plant species and up to $252M in losses per year in the U.S. on sunflower, soybeans, dry edible beans, canola, and pulse crops. It was selected as a model system for this study because of its noted long-term stability in genetic variation and also due to the availability of a fully annotated and optically mapped, published genome.

### Rhizoctonia solani in Nebraska
Long-term sustainability of soybean production in Nebraska requires minimizing disease losses and maintaining effective chemical control strategies.  For farmers, high soybean yields are critical to profit margins, where yields are reduced each year due to diseases.  Among all types of diseases in Nebraska, yield loss due to seedling diseases ranked third in 2011, causing an estimated loss of 1.35 million bushels (Bradley & Koenning, 2012).  Rhizoctonia solani is one of three pathogens most commonly associated with seedling disease, where fungicidal seed treatments are the recommended line of defense.  However, fungicide resistance in R. solani is a new threat to soybean production.  In 2012, fungicide resistance in R. solani to Azoxystrobin was reported in Louisiana, where a survey of 23 fields near the outbreak showed resistance had already spread to >65% (Olaya et al. 2012).  A major problem is that by the time that fungicide resistance is detected by growers, it may be too late to prevent spread of fungicide resistance.  This problem is compounded by a lack of knowledge of the structure of pathogen populations within fields, which directly limits our ability to design targeted and effective disease management strategies.  Beginning in 2015, our research (in collaboration with Anthony Adesemoye at the UNL WCREC) will use robust and comprehensive sampling of R. solani from soybean fields in Nebraska to determine sensitivity of isolates to commercial fungicides with different modes of action and to characterize the structure of pathogen populations within and between fields.

----
## Publications

### Peer-Reviewed Publications:
    \*Co-first author; **Corresponding author

#### 2017

1. Grunwald, N.J., S.E. Everhart, B.J. Knaus, and Z.N. Kamvar. 2017. Best practices for population genetic analyses. Phytopathology. 107:1000-1010. doi: 10.1094/PHYTO-12-16-0425-RVW
2. Dowling, M., G. Schnabel, H. Boatwright, and S.E. Everhart**. 2017. Novel gene-sequence markers for isolate tracking within Monilinia fructicola lesions. Pest Management Science. doi: 10.1002/ps.4544
3. Mirorini, T.J.J., C.G. Raetano, and S.E. Everhart**. 2017. Control of white mold of dry bean and residual activity of fungicides applied by chemigation. Crop Protection 94:192-202.

#### 2016

4. Amaradasa, B.S., and S.E. Everhart**. 2016. Effects of sublethal fungicides on mutation rates and genomic variation in fungal plant pathogen, Sclerotinia sclerotiorum. PLoS One. 11 (12): e0168079. doi: 10.1371/journal.pone.0168079.
5. Dugan, F.M., and S.E. Everhart. 2016. Cryptic species: A leitmotif of contemporary mycology has challenges and benefits for plant pathologists. Plant Health Progress. DOI:10.1094/PHP-RV-16-0046
6. de Bem, B.P., A. Bogo, S.E. Everhart, R.T. Casa, M.J. Goncalves, J.L. Marcon, L.R. Rufato, F.N. Silva, R. Allebrandt, I.C. da Cunha. 2016. Effect of four training systems on the temporal dynamics of downy mildew in two grapevine cultivars in southern Brazil. Topical Plant Pathology. DOI 10.1007/s40858-016-0110-8.
7. Tabima J.F., S.E. Everhart, M.M. Larsen, A.J. Weisberg, Z.N. Kamvar, M.A. Tancos, C.D. Smart, J.H. Chang, and N.J. Grünwald. 2016. Microbe-ID: An open source toolbox for microbial genotyping and species identification. PeerJ 4:e2279 DOI 10.7717/peerj.2279
8. Dowling, M., P.K. Bryson, H. Boatwright, J.R. Wilson, Z. Fan, G. Schnabel, S.E. Everhart, and P. Brannen. 2016. Effect of fungicide application on Monilinia fructicola population diversity and transposon movement. Phytopathology 103:1504-1512. DOI:10.1094/PHYTO-03-16-0127-R

#### 2015

9. Chen, F., S.E. Everhart*, P.K. Bryson, C.L., X. Song, X.L., G. Schnabel. 2015. Fungicide induced transposon movement in Monilinia fructicola. Fungal Genetics and Biology 85:38-44.
10. Everhart, S.E., and H. Scherm. 2015. Clonal disease foci of Monilinia fructicola during brown rot epidemics within peach tree canopies. Phytopathology 105:542-549.
11. de Bem, B.P., Bogo, A., S. Everhart, R.T. Casa, M.J. Goncalves, J.L.M. Filho, and I.C. da Cunha. 2015. Effect of Y-trellis and vertical shoot positioning training systems on downy mildew and botrytis bunch rot of grape in highlands of southern Brazil. Scientia Horticulturae 185:162-166.

#### 2014

12. Schnabel, G., F. Chen, S.E. Everhart, W.C. Bridges and X.L. Liu. 2014. Studies on sensitivity reduction in solo and mixture treatments and fungicide-induced mutagenesis in Monilinia fructicola. In: H.W. Dehne, H.B. Deising, U. Gisi, B. Fraaije, U. Gisi, D. Hermann, A. Mehl, E.C. Oerke, P.E. Russel, G. Stammler, K.H. Kuck, H. Lyr (Eds). “Modern Fungicides and Antifungal Compounds”, Vol. VII, pp 263-268. 2014 Deutsche Phytomedizinische Gesellschaft, Braunschweig, ISBN: 978-3-941261-13-6.

#### 2013

13. Everhart, S.E., A. Askew, L. Seymour, and H. Scherm. 2013. Spatio-temporal patterns of pre-harvest brown rot epidemics within individual peach tree canopies. European Journal of Plant Pathology 135: 499–509.

#### 2012

14. Everhart, S.E., A. Askew, L. Seymour, T.C. Glenn, and H. Scherm. 2012. Spatial patterns of brown rot epidemics and development of microsatellite markers for analyzing fine-scale genetic structure of Monilinia fructicola populations within peach tree canopies. Online. Plant Health Progress doi:10.1094/PHP-2012-0723-04-RS.

#### 2011

15. Everhart, S.E., A. Askew, L. Seymour, I.J. Holb, and H. Scherm. 2011. Characterization of three-dimensional spatial aggregation and association patterns of brown rot symptoms within intensively mapped sour cherry trees. Annals of Botany 108: 1195–1202.

#### 2010

16. Everhart, S.E.** 2010. Collection and identification of grapevines (Vitis) from the tree canopy of select forests in the southeastern United States. Castanea 75: 141–149.
17. Keller, H.W., and S.E. Everhart 2010. Importance of Myxomycetes in biological research and teaching. Fungi 3(1): 13–27.

#### 2009

18. Everhart, S.E., J.S. Ely, and H.W. Keller. 2009. Evaluation of tree canopy epiphytes and bark characteristics associated with corticolous myxomycetes. Botany 87: 509–517.
19. Keller, H.W., S.E. Everhart, M. Skrabal, and C.M. Kilgore. 2009. Tree canopy biodiversity in temperate forests: Exploring islands in the sky. Southeastern Biology 56: 52–74.

#### 2008

20. Everhart, S.E., and H.W. Keller. 2008. Influence of bark pH on the occurrence and distribution of tree canopy myxomycete species. Mycologia 100: 191–204.
21. Everhart, S.E., and H.W. Keller. 2008. Life history strategies of corticolous myxomycetes: The life cycle, fruiting bodies, plasmodial types, and taxonomic orders.  Fungal Diversity 29: 1–16.
22. Keller, H.W., C.M. Kilgore, S.E. Everhart, G. Carmack, C. Crabtree, and A. Scarborough. 2008. Myxomycete plasmodia and fruiting bodies: Unusual occurrences and user friendly study techniques. Fungi 1: 24–37.
23. Keller, H.W., and S.E. Everhart 2008. Myxomycete species concepts, monotypic genera, the fossil record, and additional examples for good taxonomic practice. Revista Mexicana de Micologia 27: 9–19.
24. Kilgore, C.M., H.W. Keller, S.E. Everhart, A. Scarborough, K. Snell, M. Skrabal, C. Pottorff, and J.S. Ely. 2008. Tree canopy research and student experiences using the double rope climbing method. Journal of Botanical Research Institute of Texas 2: 1309–1336.

### Books, Chapters, and R packages:

25. Keller, H.W., S.E. Everhart, and C.M. Kilgore. 2017. The Myxomycetes: Biology, life cycle, genetics and reproduction. In: Stephenson, S. and C. Lado (eds) “Myxomycetes: Biology, Systematics, Biogeography and Ecology”, Elsevier, Atlanta, GA. In press.
26. Kamvar, Z.N., Tabima, J.F., Everhart, S.E., Brooks, J.C., Krueger-Hadfield, S.A., Sotka, E. and Grunwald, N.J., 2016. Package ‘poppr’. https://cran.r-project.org/web/packages/poppr/index.html
27. Grunwald, N.J., Z.N. Kamvar, and S.E. Everhart. 2015. Population Genetics in R. Online book: http://grunwaldlab.github.io/Population_Genetics_in_R/
28. Everhart, S.E., T.F. Tabima, and N.J. Grünwald. 2014. Phytophthora ramorum. In: Dean, R.A., A. Lichens-Park, and C. Kole (eds) “Genomics of Plant Associated Fungi and Oomycetes”, Springer, New York, NY. Pp. 159-174.