---
title: "Teaching: Courses and Workshops"
output:
  html_document:
    toc: true
    toc_float: true
---

## Courses at UNL
### Ecology & Management of Plant Pathogens
This is a graduate level course on the biology, development, spread, and management of plant diseases, their causal agents and how environmental factors interact with diseases. The course is 3 credit hours and is required for students in the Plant Pathology degree specializations and the Doctor of Plant Health.  Course format is a mixture of lectures, discussions, and student presentations.  Below are pictures from a class exercise, where students turned epidemiology manuscripts into infographics!

### Disease Dynamics & Evolution
This course was designed to cover core concepts of disease ecology and pathogen emergence and evolution for undergraduates in the Microbiology program. Concepts were organism-agnostic and important for understanding infectious diseases of humans, animals, and plants. The goal of this course is to use interesting and intriguing case studies of infectious diseases to develop critical thinking as scientists. The course was designed to be appropriate for a wide variety of biology students, with interests in ecology, environmental biology, animal, plant, and human biology to microbiology, pre-vet and pre-med.  

### Intro. to Population Genetics and Epidemiology in R
This course introduces students to the R programming language, with applications in population genetics and epidemiology. This course was offered in the summer of 2016 as a . Students were taught basic skills in R syntax, data types (logical, character, numeric, etc.), data structures, sub-scripting, plotting, and packages. The goal of this course was to give students, faculty, staff, and postdocs, enough skills in R that they can access packages and resources of interest to each of them for their own research. In the future, this may be developed into a formal course and include advanced R topics, such as plotting with ggplot, using apply functions to avoid loops, and R Markdown for producing presentations, reports, and websites in R. 
#### A semester-long version will be offered in Fall 2018


## Workshops

### Intro to R for Plant Pathologists
This workshop was developed in the summer of 2017 as a way to introduce scientists to R, using specific examples from plant pathology. Participants learn how to: read in data, manipulate data, summarize and visualize data, perform comparisons, find and load packages, and troubleshoot common problems. This workshop uses base packages and newer tools, such as dplyr and ggplot2.

#### This workshop has been or will be offered:
- May 24th, 2017 at the University of Nebraska, Lincoln, NE (50+ participants)
 https://everhartlab.github.io/IntroR/
- June 14th, 2017 at the APS North Central Division Meeting in Champaigne, IL (20+)
- October 16th, 2017 at Ohio State University, Columbus, OH
https://everhartlab.github.io/IntroR-at-OSU/

### Population Genetics in R
Analyzing population genetic data can be challenging because it often requires the use of different softwares to perform all your analyses.  However, R is a great way to analyze your data all in one place.  A milestone in population genetic analyses in R was the development of the R package poppr by Zhian Kamvar et al. (2014).  The poppr package places these analyses all under one roof in an easy-to-use format.  I was fortunate to work with Zhian on poppr while in the Grunwald Lab at Oregon State University.  To make analyzing your population genetic data using poppr even easier, we wrote the following step-by-step tutorial: Population Genetic Analysis in R

----