---
title: "Time Management"
output:
  html_document:
    toc: true
    toc_float: true
---

<br>

### Productivity
We all want to be highly productive and recognized for our efforts.  You can probably think of people that you would call highly productive. How do they get so much done?  How do they publish so much?

<br>

### What's the secret?
Effective time management and prioritization is the secret.  If you are already working 40-50 hours per week, you shouldn't beat yourself up to work more hours, you should re-evaluate how you are spending your time.  Focus on improving the quality of the hours you already work.  Identifying the items that are the best use of your time can be challenging and subjective. As a scientist, I like to approach things from an objective and quantitative perspective, so I've adopted the following technique to create a prioritization list using the following steps:

1. Value your work, 
2. Value your time, 
3. Prioritize using values of work + time, 
4. Eliminate potential pitfalls, 
5. Set your priority list in motion.

---

<br>

### 1. The Value of Your Work
I like to use a value system to identify "high pay-off" and "low pay-off" tasks. A great example that we can use for this exercise is to evaluate all of the possible items that might be added to an academic CV. For example, presenting a poster or giving a presentation should receive higher priority than being asked to review a paper for a journal.  Among those items that can be added to a CV, highest priority should be given to peer-reviewed, original research articles and review papers.  And among those, highest priority should be given to manuscripts where you will be listed as the first or corresponding author.  **These publications are the most valuable** and are the first piece of your CV that will be used to evaluate productivity.  Low priority should be given to non-peer reviewed items, which includes some symposia proceedings, reviewing manuscripts, and book reviews.  

<br>

#### Priority for Your CV 
**HPO** = high pay-off; **LPO** = low pay-off

1. first author on peer-reviewed manuscripts and reviews (HPO)
2. middle author on peer-reviewed manuscripts and reviews (HPO)
3. teaching experience as TA or instructor (HPO)
4. creating own professional website (HPO)
3. first author disease notes and research notes (HPO)
4. first author presentations (HPO)
5. first author posters (HPO)
5. middle author for presentations and posters (LPO)
6. non-peer reviewed articles, such as magazine articles in popular press (LPO)
7. book reviews (LPO)
9. active participation in your scientific society (LPO)
8. reviewing manuscripts (LPO)
10. active participation in your local club (LPO)

<br>

### 2. The Value of Your Time
Some tasks don't take very long, maybe a few hours of your day.  Other tasks take several years, such as completing a chapter of your dissertation.  It's important to consider how much effort is required for each of the tasks you've just prioritized.  For this, we can categorize them into "high effort" and "low effort".  For example, being asked to be a middle author for a presentation or poster will likely require low effort, whereas being the first author would be high effort.

<br>

#### Effort of Items on Your CV 
**LE** = low effort; **HE** = high effort

1. middle author for presentations and posters (LE)
2. middle author on peer-reviewed manuscripts and reviews (LE)
3. active participation in your scientific society (LE)
5. creating own professional website (LE)
8. non-peer reviewed articles, such as magazine articles in popular press (HE)
9. book reviews (HE)
7. first author posters (HE)
6. first author presentations (HE)
6. first author disease notes and research notes (HE)
5. teaching experience as TA or instructor (HE)
8. reviewing manuscripts (HE)
9. first author on peer-reviewed manuscripts and reviews (HE)
10. active participation in your local club (HE)

<br>

### 3. Maximize Pay-off & Effort
The maximum return on your investment will come from high pay-off tasks that require low effort. Unfortunately, there are few items that will fit this category. Although something like a chapter of your dissertation is high pay-off, the effort to complete that task decreases over time.  Here is our example list above, ordered according to the sum of the ranking of each item in both lists. For example, #1 on the pay-off list is first author on peer-reviewed manuscripts and reviews.  That task is ranked at #9 on our effort list.  Thus, the combined score for that task is 10.  After adding the rank for pay-off and effort for each task, we re-order the list to show tasks with the smallest sum (highest pay-off + least effort) at the top of the list.

<br>

#### Combined List
1. middle author on peer-reviewed manuscripts and reviews (HPO + LE)
2. creating own professional website (HPO + LE)
3. **middle author for presentations and posters (LPO + LE)**
4. first author on peer-reviewed manuscripts and reviews (HPO + HE)
5. teaching experience as TA or instructor (HPO + HE)
6. first author disease notes and research notes (HPO + HE)
7. first author presentations (HPO + HE)
8. first author posters (HPO + HE)
9. non-peer reviewed articles, such as magazine articles in popular press (LPO + HE)
10. **active participation in your scientific society (LPO + LE)**
11. book reviews (LPO + HE)
12. reviewing manuscripts (LPO + HE)
13. active participation in your local club (LPO + HE)

<br>

### 4. Pitfalls
Some of the items listed above were both low pay-off and low effort (bold).  Other items are low pay-off and high effort (numbers 9 to 13).  Both of these categories represent time sinks and pitfalls that we should avoid. This is because low effort tasks do not take much effort, so it is easy to spend too much time here.  However, due to the low pay-off from these activities, we don't get much in return.  We should minimize the amount of time spent on these activities.  Likewise, items listed as low pay-off and high effort are definitely not worth much time on a daily basis.  These will take a lot of time to complete with very little reward.  Make sure to eliminate these items from your priority list and focus only on the most important tasks.  

<br>

### Priority List
1. middle author on peer-reviewed manuscripts and reviews (HPO + LE)
2. creating own professional website (HPO + LE)
4. first author on peer-reviewed manuscripts and reviews (HPO + HE)
5. teaching experience as TA or instructor (HPO + HE)
6. first author disease notes and research notes (HPO + HE)
7. first author presentations (HPO + HE)
8. first author posters (HPO + HE)

<br>

### 5. Get Started Right
Now that our priority list has been reduced and is ranked according to how much it will benefit us and use our time, we can plan our day and even start planning the semester.  A great way to get started on this list is to **begin with items that are high pay-off and low effort**.  This way you can feel success and it will pay-off for you quickly.  In our example, that would include contributing as a co-author for someone else's manuscript and creating a professional website to highligh our interests and work.  The third item on the list is a big one, working on a first author peer-reviewed manuscript or review article.  **To accomplish projects that are both high pay-off and require high effort, the key is to spend time on this on a daily basis.**  Remember, spending just 10 minutes per day will turn into an entire 40-hour work week of time by the end of a year.  So, spend time on those activities daily to reduce the burden.

In my next article, I will describe how to create a plan for your work using a Gannt Chart.  Combining this priority listing system with a Gannt Chart is an excellent way to help maximize your efforts without spending more time.  Focus on quality, not quantity.


<!-- ```{r echo=FALSE} -->
<!-- library(gridExtra) -->
<!-- library(grid) -->
<!-- d <- matrix(data = c(1,2,3,4), dimnames = list(c("High pay-off", "Low pay-off"), c("High effort", "Low Effort")), nrow = 2, ncol = 2, byrow = TRUE) -->
<!-- grid.table(d) -->
<!-- ``` -->



